# Generated by Django 4.2.5 on 2024-01-27 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_order_orderitem_order_products_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(choices=[('delivery_boy', 'Delivery Boy'), ('plumber', 'Plumber')], max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('full_address', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car')], max_length=10)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('license', models.FileField(upload_to='licenses/')),
                ('highest_education', models.CharField(choices=[('10th', '10th Level'), ('12th', '12th Level'), ('degree', 'Degree')], max_length=10)),
                ('languages_known', models.CharField(max_length=255)),
                ('years_of_experience', models.CharField(choices=[('0', '0'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-5', '3-5'), ('more', 'More than 5')], max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
