# Generated by Django 4.2.5 on 2024-02-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_customerservicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
