# Generated by Django 4.2.5 on 2024-02-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_customerservicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservicerequest',
            name='work_status',
            field=models.CharField(default='Not Completed', max_length=20),
        ),
    ]
