# Generated by Django 4.2.5 on 2024-04-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_title',
        ),
    ]
