# Generated by Django 4.2.5 on 2024-04-05 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_jobapplication_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlumberJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('full_address', models.TextField()),
                ('highest_education', models.CharField(max_length=10)),
                ('languages_known', models.CharField(max_length=255)),
                ('years_of_experience', models.CharField(max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
